const productTypes = [
    'All',
    'A5 Notebook',
    'A5 Planner',
    'Activity',
    'Apothecary',
    'Artwork',
    'Bags',
    'Bamboo Tableware',
    'Best Sellers',
    'Books',
    'Candles',
    'Clutches',
    'Desk Accessories',
    'Drinkware',
    'Earrings',
    'Enamel Pins',
    'Folder',
    'Folio',
    'Food',
    'Garden',
    'Handbags',
    'Hats',
    'In Fruition',
    'Jewelry',
    'Kitchen',
    'Minimalist Collection',
    'Minimalist Folio',
    'New Arrivals',
    'Notebook',
    'Objects',
    'Pens & Pencils',
    'Planners',
    'Poketo Exclusives',
    'Poketo Home',
    'Prints',
    'realted-catalonia',
    'Sale',
    'Sample Sale',
    'Scarf',
    'Shoulder Bags',
    'Skincare',
    'Socks',
    'Sunglasses',
    'Tableware',
    'Tech',
    'Textiles',
    'Wallets',
    'Wallets/Cases/Clutches',
    'wellness'
]

export default productTypes;